### ISSUE TITLE
Unable to run multiple step definitions through wdio config

### ISSUE THREAD

**Issue by GGuru** [webdriverio/wdio-cucumber-framework#10]
This is my config. It is not working if i pass a directory to require parameter. If i pass a specific step definition file, it works. So, I can't run multiple step definitions with this. 

exports.config = {

```
/**
 * server configurations
 */
host: '172.20.197.113',
port: 4444,

/**
 * specify test files
 */
specs: [
    './runner-specs/cucumber/features/*.feature'
],

/**
 * capabilities
 */
capabilities: [{
    browserName: 'chrome',
    version: '42.0'
}],

/**
 * test configurations
 */
logLevel: 'silent',
coloredLogs: true,
screenshotPath: 'shots',
waitforTimeout: 10000,
framework: 'cucumber',

reporters: ['dot'],
reporterOptions: {
    outputDir: './'
},

cucumberOpts: {
    require: ['./runner-specs/cucumber/features/step_definitions/']
}
```

};

**Comment by attila** [comment]
I noticed that does not work either. Tried with relative paths and realpaths using `path.resolve()` to no avail.
```
ERROR: ENOENT: no such file or directory, realpath '/home/attila/example/app/test/features/step_definitions/**/*.js'
```
My guess is that the pattern is not matched properly. One workaround is to omit the require in `cucumberOpts` and stick all step definition files to their default location, i.e `features/step_definitions` and cucumber will pick them up.

**Comment by twKrash** [comment]
Seems to me that * in path is not working.

**Comment by sarneeh** [comment]
Have the same problem here.

**Comment by mike-suggitt** [comment]
+1 this is really irritating

**Comment by mike-suggitt** [comment]
FWIW I've done a workaround for the time being that aggregates files together using an `index.steps.js` file

```
var world = require('../support/world');

var steps = [
    require('./action.steps'),
    require('./form.steps'),
    require('./navigation'),
    require('./verify.steps')
];

module.exports = function() {
    this.World = world;

    steps.forEach(function(step) {
        step.call(this);
    }.bind(this));
};
```

**Comment by webmagit** [comment]
Removing the asterisk worked for me -

```require: ['./features/step-definitions/']```

**Comment by mike-suggitt** [comment]
@webmagit Really? I (wrongly?) assumed the paths were globbed?

**Comment by christian-bromann** [comment]
@mike-suggitt I just propagate the values to Cucumber directly so if Cucumber .. so might be that Cucumber handles it differently

**Comment by christian-bromann** [comment]
> I (wrongly?) assumed the paths were globbed?

Revisit issue and yes seems like cucumber handles this differently. I don't think it is a good idea to change this behavior as it would require to add another dependency. I added a note to the parameter description.

**Comment by devth** [comment]
Referencing the directory doesn't work for me. Gives:

```
ERROR: Cannot find module './src/test/features/step_definitions'
```
