### ISSUE TITLE
Generating a cucumber json file

### ISSUE THREAD

**Issue by javacoldbrew** [webdriverio/wdio-cucumber-framework#103]
Is it possible to generate a cucumber json file with this framework that includes which tests fail/pass?

For example in cucumber, you could simply do:

"cucumber-js ./tests/features -r ./tests/steps -f json:./reports/cucumber/cucumber_report.json"

**Comment by christian-bromann** [comment]
@javacoldbrew you can use the [wdio-json-reporter](https://www.npmjs.com/package/wdio-json-reporter) for this. Join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for these kind of questions. This is not necessary an issue.
