### ISSUE TITLE
Error: Expr.chartAt is not a function

### ISSUE THREAD

**Issue by JEHAL981** [webdriverio/wdio-cucumber-framework#107]
I updated wdio-cucumber-framework  to 2.0.0 when I execute my test I get the following message. I have current cucumber.js installed (4.1.0).
```
ERROR: expr.charAt is not a function
chrome
Type    at tokenize /node_modules/cucumber-tag-expressions/lib/tag_expression_parser.js:87:20)
```
![screen shot 2018-03-31 at 12 10 12](https://user-images.githubusercontent.com/35871107/38162651-f09afbdc-34dc-11e8-8ab3-1d3daed87515.png)

**Comment by BorisOsipov** [comment]
What is your cucumber opts? Especially tags.
Please share with us.

**Comment by JEHAL981** [comment]
Thanks for your help @BorisOsipov 

Happy Easter! 

`cucumberOpts: {
        require: [
            './features/step_definitions/HomePageStepDefs.js',
            './features/step_definitions/LoginPageStepDefs.js.js'


        ],
        backtrace: false,
        compiler: ['js:babel-core/register'],
        dryRun: false,
        failFast: false,
        format: ['pretty'],
        colors: true,
        snippets: true,
        source: true,
        strict: false,
        tags: ['@chasers', '@complete'],
        timeout: 280000,
        ignoreUndefinedDefinitions: true,
    },`

**Comment by BorisOsipov** [comment]
`tags` should be a [tag expression](https://docs.cucumber.io/tag-expressions/) 

try to change `['@chasers', '@complete']` to '@chasers and @complete'

Happy Easter!

**Comment by christian-bromann** [comment]
Yep, this has updated with the cucumber update. We probably need to update the readme. Will create a separate issue for this.

**Comment by devth** [comment]
Was an issue created to track this? I couldn't find it but maybe I missed it.

**Comment by harishkalaiselvan** [comment]
Can you let me know the status on this issue?

**Comment by BorisOsipov** [comment]
@devth @harishkalaiselvan there is no issue.

see my comment on https://github.com/webdriverio/wdio-cucumber-framework/issues/107#issuecomment-377694195
