### ISSUE TITLE
Wdio-cucumber-framework 2.0.x is broken

### ISSUE THREAD

**Issue by BorisOsipov** [webdriverio/wdio-cucumber-framework#113]
There are basic things that doesn't work at all in spite of the fact that travis build is green.
E.g.:
https://github.com/webdriverio/wdio-cucumber-framework/issues/108
https://github.com/webdriverio/wdio-cucumber-framework/issues/111
https://github.com/webdriverio/wdio-cucumber-framework/issues/112

I can't call such version `production ready`.
It causes to fail users test after update and impossible to use `2.0.X` version.

@christian-bromann maybe we will move 2.0.0 release to the alpha\beta status and hence avoid negative feedback from users?
At the same time we will still be able to receive some feedback from early adopters.

//cc @mhoyer

**Comment by jonsmithers** [comment]
As someone who got burned by an issue in 2.0 (i.e. #114), I think I agree. I'm glad I saw this and thought to revert to 1.1.1.

**Comment by wswebcreation** [comment]
@BorisOsipov @christian-bromann 

I think all issues are gone if PR https://github.com/webdriverio/wdio-cucumber-framework/pull/137 will be merged. I already provided feedback on the PR.

I also know that V5 is also coming out soon, but I wonder if we can still merge the PR and bring out a new release for people who still want to use webdriver.io V4 with the latest version of this module.

Tnx for your time

Grtz

Wim
