### ISSUE TITLE
Cucumber 4.2.1 fails  due to the new "order" option, but 4.1.0 works

### ISSUE THREAD

**Issue by vladgolubev** [webdriverio/wdio-cucumber-framework#116]
Hey, just installed the https://github.com/webdriverio/cucumber-boilerplate and it fails due to error

<details>
<summary>Expand stack trace</summary>

```
Type    at orderTestCases (/home/circleci/repo/node_modules/cucumber/src/cli/helpers.js:74:28)
    at Object.<anonymous> (/home/circleci/repo/node_modules/cucumber/src/cli/helpers.js:41:3)
    at Generator.next (<anonymous>)
    at Generator.tryCatcher (/home/circleci/repo/node_modules/bluebird/js/release/util.js:16:23)
    at PromiseSpawn._promiseFulfilled (/home/circleci/repo/node_modules/bluebird/js/release/generators.js:97:49)
    at Promise._settlePromise (/home/circleci/repo/node_modules/bluebird/js/release/promise.js:574:26)
    at Promise._settlePromise0 (/home/circleci/repo/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/home/circleci/repo/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/home/circleci/repo/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/home/circleci/repo/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/home/circleci/repo/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:794:20)
    at tryOnImmediate (timers.js:752:5)
    at processImmediate [as _immediateCallback] (timers.js:729:5)
```
</details>

If you check [cucumber changelog](https://github.com/cucumber/cucumber-js/blob/master/CHANGELOG.md#420-2018-04-03) for version 4.2.0 there is a new option `order` now required to pass into [getTestCasesFromFilesystem](https://github.com/webdriverio/wdio-cucumber-framework/blob/master/lib/adapter.js#L76) which webdriver adapter not yet supports.

I had to lock down version to 4.1.0 to make tests work.

Looks like a small fix, thanks in advance!

**Comment by christian-bromann** [comment]
@vladgolubev feel free to propose a PR

**Comment by swissmanu** [comment]
will take care of it

**Comment by Xotabu4** [comment]
I overriden cucumber version in package-lock for a while:

```
"wdio-cucumber-framework": {
      "version": "2.0.1",
      "resolved": "https://registry.npmjs.org/wdio-cucumber-framework/-/wdio-cucumber-framework-2.0.1.tgz",
      "integrity": "sha512-JpFiVJxLkEj7kNALVezFX87UZgDf2y4o7whO77+J8wtNsOoLs0vNlmAjZr1Kme5eb3jVZUoeQkVWXlE+Xw7Gkg==",
      "requires": {
        "babel-runtime": "6.26.0",
        "cucumber": "4.1.0",
        "glob": "7.1.2",
        "is-glob": "4.0.0",
        "mockery": "2.1.0",
        "wdio-sync": "0.7.1"
      },
      "dependencies": {
        "cucumber": {
          "version": "4.1.0",
```

**Comment by Nibblesh** [comment]
For anyone looking for a temp workaround until this is accepted,

if you're using yarn, you can add this to the package.json

```json
"resolutions": {
    "wdio-cucumber-framework": "https://github.com/swissmanu/wdio-cucumber-framework.git#order-option"
}
```

**Comment by BorisOsipov** [comment]
@christian-bromann can you release a new version with fix for this issue?

**Comment by RenanChagas** [comment]
@BorisOsipov  Hi Boris, Sorry I didnt understand how to fix this issue

What should I do ?

**Comment by RenanChagas** [comment]
Thanks for the quick reply @BorisOsipov 
Do you know what version can I downgrade on "yarn.lock" so I can run my steps files while the error is being fixed in the released version ?

**Comment by BorisOsipov** [comment]
@RenanChagas  you can downgrade `cucumber` version to
`"cucumber": "4.1.0"`

**Comment by vladgolubev** [comment]
@RenanChagas  for yarn use https://yarnpkg.com/en/docs/selective-version-resolutions#search

**Comment by RenanChagas** [comment]
I deleted the "node_modules" and "yarn.lock" and it still getting the same error

**package.json**

> {
>   "name": "my-app",
>   "version": "0.1.0",
>   "private": true,
>   "dependencies": {
>     "chai": "^4.1.2",
>     "react": "^16.3.2",
>     "react-dom": "^16.3.2",
>     "react-scripts": "1.1.4",
>     "selenium-standalone": "^6.14.0",
>     "wdio-cucumber-framework": "2.0.1",
>     "webdriverio": "4.12.0",
>     "cucumber": "4.1.0"
>   },
>   "scripts": {
>     "start": "react-scripts start",
>     "build": "react-scripts build",
>     "test": "react-scripts test --env=jsdom",
>     "eject": "react-scripts eject"
>   },
>   "resolution": {
>     "cucumber": "4.1.0",
>     "cucumber-expressions": "5.0.13"
>   }
> }
>

**Comment by vladgolubev** [comment]
@RenanChagas you have a typo

It's `resolutions` not `resolution`

**Comment by RenanChagas** [comment]
@vladgolubev thank you, but unfortunetely I'm still getting the same error :(

Can anyone help me ? I dont know what else can it be.

`https://github.com/RenanChagas/my-app.git`

**Comment by vladgolubev** [comment]
@RenanChagas hmmm, now you downgraded to version 2, and when I try to run your repo locally I get this

![image](https://user-images.githubusercontent.com/3817380/38921308-18aef32e-42fe-11e8-99bb-c6cf79028bf9.png)

Maybe you forgot to push some latest changes? Can you please update your example to make it run?

**Comment by BorisOsipov** [comment]
@RenanChagas update to wdio-cucumber-framework `2.1.0` - it fixes your issue.

**Comment by RenanChagas** [comment]
Thank you @vladgolubev and @BorisOsipov !!!

**Comment by Nibblesh** [comment]
@RenanChagas 

for future reference, here's where you went wrong on the package json


Working package.json below
```
"resolutions": {
  "wdio-cucumber-framework/cucumber": "4.1.0"
}
```

as the issue was caused by the cucumber dependency in the wdio-cucumber-framework, we need to tell yarn to use version 4.1 when referenced by wdio-cucumber-framework

**Comment by RenanChagas** [comment]
Thank you @Nibblesh
