### ISSUE TITLE
All scenarios start at once

### ISSUE THREAD

**Issue by motycka** [webdriverio/wdio-cucumber-framework#129]
Hello, I have recently upgraded to version 2.x and with that upgrade, my scenarios are now starting all in parallel and it appears they run in the same browser window. This does not seem OK to me, since every cucumber scenario should establish it's own, independent context.

Example feature file:
```
Feature: Scenarios

    Scenario: My first scenario should run first

        When I run my first scenario
        Then my first scenario needs to do it's thing

    Scenario: My second scenario should run after

        When I run my second scenario
        Then my second scenario needs to do it's thing

    Scenario: My third scenario should run last

        When I run my third scenario
        Then my third scenario needs to do it's thing
```

log:
```
  Feature: Scenarios

    Scenario: My first scenario should run first

    Scenario: My second scenario should run after

    Scenario: My third scenario should run last
      I run my first scenario
      my first scenario needs to do it's thing
      I run my second scenario
      my second scenario needs to do it's thing
      I run my third scenario
      my third scenario needs to do it's thing

6 steps (6 passed, 0 failed, 0 pending)
```

Is it a setup thing, or a bug?

This was last OK in version 1.1.1

**Comment by christian-bromann** [comment]
@motycka please describe how do you run webdriverio? Are you using wdio testrunner? What are you package versions?

**Comment by motycka** [comment]
@christian-bromann yes, `wdio` test runner, I believe.

```

**Comment by wswebcreation** [comment]
@motycka 

Is this problem already solved for you? And if not, can you please provide some more info like your step implementation.

**Comment by woolter** [comment]
We can close this issue.
It was solve with https://github.com/webdriverio/wdio-cucumber-framework/pull/147

**Comment by BorisOsipov** [comment]
Yes. Thanks @woolter
