### ISSUE TITLE
Scenario outline is not working after scenario

### ISSUE THREAD

**Issue by AbinashB** [webdriverio/wdio-cucumber-framework#134]
if a feature file contains Scenario outline first then scenario it is working fine, But reverse one not working.

Working fine:
feature: 
     scenario:
     scenario outline:

Not working:
feature:
     scenario outline:
     scenario:
      
logs: ERROR: Parser errors:
(9:9): expected: #EOF, #Comment, #BackgroundLine, #TagLine, #ScenarioLine, #ScenarioOutlineLine, #Empty, got "my step"

**Comment by christian-bromann** [comment]
@AbinashB this is more an issue with cucumber-js. This package doesn't parse the feature file in any way.
