### ISSUE TITLE
wdio-sync dependency

### ISSUE THREAD

**Issue by ricoli** [webdriverio/wdio-cucumber-framework#14]
Am I correct in assuming that the wdio-sync dependency is only used if ```sync: true``` is in the configuration? If so, wouldn't it be best that wdio-sync be changed to a peer dependency?
I ask this because I have a test suite that is run asynchronously and yet fibers has to be compiled and installed upon npm install, taking quite some time, when I suppose it's not even used.

**Comment by christian-bromann** [comment]
Sorry but the wdio-sync package is used even if you have set `sync: false`. It contains the main logic around retrying tests and executing hooks. I don't think we can move it to be a peerDependency.
