### ISSUE TITLE
Wrong steps reporting in 2.2.1

### ISSUE THREAD

**Issue by Tallyb** [webdriverio/wdio-cucumber-framework#140]
=> Bug report.  
Using spec reporter. 
Assume my feature is as follow: 
```
 Feature: error
Scenario: x
   When do X
Scenario: y
  When do Y
  When do Z
```
The reporting will report for the subsequent steps starting from the top (with the correct number of steps). So the reporting will look like: 
```
Scenario x
   When do X
Scenario y
   When do X <= instead of reporting Y
   When do Y 
[When do Z is not reported]
```
2.2.0 does not have the problem.

**Comment by Rob-Meijeren** [comment]
There is currently a pull request open to fix this #139
