### ISSUE TITLE
Scenario outline reporting behaviour missing example values and indentation issues

### ISSUE THREAD

**Issue by filfreire** [webdriverio/wdio-cucumber-framework#142]
I have reasons to believe that both the indentation and the printing of parameters in each scenario outline execution is not working properly and affects reporters like `spec` for the latest version of wdio-cucumber-framework (`2.2.2`).

Taking into account this issue https://github.com/wswebcreation/wdio-multiple-cucumber-html-reporter/issues/7 and also as a follow-up to issue https://github.com/webdriverio/wdio-cucumber-framework/issues/111 it seems that for example, for version `1.1.0` this issue isn't present, and both the indentation of the scenario outline execution as well as the parameters of each example line are properly passed to the reporters (tested with `spec` and `wdio-multiple-cucumber-html-reporter`), where as for version `2.2.2` this doesn't seem to be happening properly.

Bellow are some screenshots:
For `1.1.0` the Example values appear in each execution, and the scenario is properly indented:
![spec_formatter](https://user-images.githubusercontent.com/11976836/44032887-d7aabe50-9f08-11e8-8d3c-6fc2443556ef.png)

For `2.2.2` the example values don't appear, and in the case of spec reporter, the scenarios execution indents endlessly:
![spec_formatter_wdio-cuc-222](https://user-images.githubusercontent.com/11976836/44032886-d788afae-9f08-11e8-8f2f-75718012739a.png)

My environment is:
- node `v8.9.3`
- npm `5.5.1`
- wdio `v4.13.1`
- wdio-cucumber-framework `2.2.2`
- wdio-multiple-cucumber-html-reporter `0.1.3`

/cc @christian-bromann @wswebcreation @shabfactor

**Comment by christian-bromann** [comment]
@woolter are you sure it is the same? This looks more like an issue with the spec reporter

**Comment by BorisOsipov** [comment]
@christian-bromann I am almost sure it is wdio-cucumber v2 issue. It reports suited:start events in strange order

**Comment by filfreire** [comment]
@woolter @BorisOsipov @christian-bromann 
This is different from issue #129. My issue is with scenario outlines and I have no issues with parallel test execution, because i've setup the test config to run 1 scenario at a time sequentially. 

The bigger problem with this issue besides the indentation of each scenario outline execution on `spec` reporter, is that, independently of the reporter you use (`spec`, `junit`, `wdio-multiple-cucumber-html-reporter`, the example data isn't passed to the reporter, and you end up with with test execution results displayed with empty test data parameters, like shown on issue https://github.com/wswebcreation/wdio-multiple-cucumber-html-reporter/issues/7

**Comment by woolter** [comment]
@BorisOsipov @christian-bromann @filfreire 
Yes, I'm sure. The issue is with wdio-cucumber-framework, no with spec, if you use allure is the same problem as you can see in [#|30](https://github.com/webdriverio/wdio-cucumber-framework/issues/130)

**Comment by wswebcreation** [comment]
Regarding the missing of the example values I have the following. Below is based on the following Scenario Outline

```bash
Feature: Create scenario outline feature

    Scenario Outline: a scenario outline header1:<header1> and header2:<header2>
        Given an outline <header1> step
        And an outline <header2> step

        Examples:
            | header1   | header2 |
            | outline 1 | value1  |
            | outline 2 | value2  |
```

When I look at the `cucumberEventListener.js` file there is a `onPickleAccepted` that holds a `scenario`. When I look at the scenario it will already have the correct example values in it, see below

```json
{
  "name": "a scenario outline header1:outline 1 and header2:value1",
  "language": "en",
  "steps": [
    {
      "text": "an outline outline 1 step",
      "arguments": [],
      "locations": [
        {
          "line": 12,
          "column": 13
        },
        {
          "line": 6,
          "column": 15
        }
      ]
    }
  ],
  "tags": [],
  "locations": [
    {
      "line": 12,
      "column": 13
    },
    {
      "line": 5,
      "column": 5
    }
  ]
}
```

When I look at the rest of the events where scenario's are retrieved the raw scenario's, see below, are used. Can't the scenario and stepdata from the `onPickleAccepted` be used?

```json
{
  "type": "ScenarioOutline",
  "tags": [],
  "location": {
    "line": 5,
    "column": 5
  },
  "keyword": "Scenario Outline",
  "name": "a scenario outline header1:<header1> and header2:<header2>",
  "steps": [
    {
      "type": "Hook",
      "location": {
        "line": 42,
        "column": 0,
        "uri": "__tests__/step_definitions/all.steps.js"
      },
      "keyword": "Hook",
      "text": ""
    },
    {
      "type": "Step",
      "location": {
        "line": 6,
        "column": 9
      },
      "keyword": "Given ",
      "text": "an outline <header1> step"
    },
    {
      "type": "Step",
      "location": {
        "line": 7,
        "column": 9
      },
      "keyword": "And ",
      "text": "an outline <header2> step"
    },
    {
      "type": "Hook",
      "location": {
        "line": 70,
        "column": 0,
        "uri": "__tests__/step_definitions/all.steps.js"
      },
      "keyword": "Hook",
      "text": ""
    }
  ],
  "examples": [
    {
      "type": "Examples",
      "tags": [],
      "location": {
        "line": 9,
        "column": 9
      },
      "keyword": "Examples",
      "name": "",
      "tableHeader": {
        "type": "TableRow",
        "location": {
          "line": 10,
          "column": 13
        },
        "cells": [
          {
            "type": "TableCell",
            "location": {
              "line": 10,
              "column": 15
            },
            "value": "header1"
          },
          {
            "type": "TableCell",
            "location": {
              "line": 10,
              "column": 27
            },
            "value": "header2"
          }
        ]
      },
      "tableBody": [
        {
          "type": "TableRow",
          "location": {
            "line": 11,
            "column": 13
          },
          "cells": [
            {
              "type": "TableCell",
              "location": {
                "line": 11,
                "column": 15
              },
              "value": "outline 1"
            },
            {
              "type": "TableCell",
              "location": {
                "line": 11,
                "column": 27
              },
              "value": "value1"
            }
          ]
        },
        {
          "type": "TableRow",
          "location": {
            "line": 12,
            "column": 13
          },
          "cells": [
            {
              "type": "TableCell",
              "location": {
                "line": 12,
                "column": 15
              },
              "value": "outline 2"
            },
            {
              "type": "TableCell",
              "location": {
                "line": 12,
                "column": 27
              },
              "value": "value2"
            }
          ]
        }
      ]
    }
  ]
}
```
