### ISSUE TITLE
Can't Install on Redhat NPM install fails  

### ISSUE THREAD

**Issue by obender** [webdriverio/wdio-cucumber-framework#148]
When I run 
npm i wdio-cucumber-framework 

Linux Version: 
Linux tavdtrh6as2 2.6.32-642.el6.x86_64 #1 SMP Tue May 10 17:27:01 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
Red Hat Enterprise Linux Server release 6.5 (Santiago)

I get the error below:
[as2user@tavdtrh6as2 ui]$ npm i wdio-cucumber-framework

> fibers@1.0.15 install /home/as2user/p4/main/apimcommon/ui/node_modules/fibers
> node build.js || nodejs build.js

make: Entering directory `/home/as2user/p4/main/apimcommon/ui/node_modules/fibers/build'
  CXX(target) Release/obj.target/fibers/src/fibers.o
In file included from /usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/memory:83,
                 from /tmp/.gyp/8.11.4/include/node/v8.h:21,
                 from /tmp/.gyp/8.11.4/include/node/node.h:63,
                 from ../src/coroutine.h:1,
                 from ../src/fibers.cc:1:
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/shared_ptr.h: In member function ‘virtual void* std::_Sp_counted_deleter<_Ptr, _Deleter, _Alloc, _Lp>::_M_get_deleter(const std::type_info&)’:
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/shared_ptr.h:146: error: cannot use typeid with -fno-rtti
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/shared_ptr.h: In member function ‘virtual void* std::_Sp_counted_ptr_inplace<_Tp, _Alloc, _Lp>::_M_get_deleter(const std::type_info&)’:
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/shared_ptr.h:204: error: cannot use typeid with -fno-rtti
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/shared_ptr.h: In constructor ‘std::__shared_ptr<_Tp, _Lp>::__shared_ptr(std::_Sp_make_shared_tag, _Alloc, _Args&& ...)’:
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/shared_ptr.h:861: error: cannot use typeid with -fno-rtti
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/shared_ptr.h: In function ‘_Del* std::get_deleter(const std::__shared_ptr<_Tp2, _Lp>&)’:
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/shared_ptr.h:1005: error: cannot use typeid with -fno-rtti
In file included from /tmp/.gyp/8.11.4/include/node/node.h:63,
                 from ../src/coroutine.h:1,
                 from ../src/fibers.cc:1:
/tmp/.gyp/8.11.4/include/node/v8.h: At global scope:
/tmp/.gyp/8.11.4/include/node/v8.h:334: error: expected unqualified-id before ‘using’
/tmp/.gyp/8.11.4/include/node/v8.h: In constructor ‘v8::MaybeLocal<T>::MaybeLocal()’:
/tmp/.gyp/8.11.4/include/node/v8.h:351: error: ‘nullptr’ was not declared in this scope
/tmp/.gyp/8.11.4/include/node/v8.h: In member function ‘bool v8::MaybeLocal<T>::IsEmpty() const’:
/tmp/.gyp/8.11.4/include/node/v8.h:358: error: ‘nullptr’ was not declared in this scope
/tmp/.gyp/8.11.4/include/node/v8.h: In member function ‘bool v8::MaybeLocal<T>::ToLocal(v8::Local<S>*) const’:
/tmp/.gyp/8.11.4/include/node/v8.h:366: error: ‘nullptr’ was not declared in this scope
/tmp/.gyp/8.11.4/include/node/v8.h: In constructor ‘v8::Eternal<T>::Eternal()’:
/tmp/.gyp/8.11.4/include/node/v8.h:395: error: ‘nullptr’ was not declared in this scope
/tmp/.gyp/8.11.4/include/node/v8.h: In constructor ‘v8::Eternal<T>::Eternal(v8::Isolate*, v8::Local<S>)’:
/tmp/.gyp/8.11.4/include/node/v8.h:397: error: ‘nullptr’ was not declared in this scope
/tmp/.gyp/8.11.4/include/node/v8.h: In member function ‘bool v8::Eternal<T>::IsEmpty() const’:
/tmp/.gyp/8.11.4/include/node/v8.h:402: error: ‘nullptr’ was not declared in this scope
/tmp/.gyp/8.11.4/include/node/v8.h: In member function ‘bool v8::WeakCallbackInfo<T>::IsFirstPass() const’:
/tmp/.gyp/8.11.4/include/node/v8.h:442: error: ‘nullptr’ was not declared in this scope
/tmp/.gyp/8.11.4/include/node/v8.h: In constructor ‘v8::Global<T>::Global()’:
/tmp/.gyp/8.11.4/include/node/v8.h:776: error: ‘nullptr’ was not declared in this scope
/tmp/.gyp/8.11.4/include/node/v8.h: In constructor ‘v8::Global<T>::Global(v8::Global<T>&&)’:
/tmp/.gyp/8.11.4/include/node/v8.h:801: error: ‘nullptr’ was not declared in this scope
/tmp/.gyp/8.11.4/include/node/v8.h: In member function ‘v8::Global<T>& v8::Global<T>::operator=(v8::Global<S>&&)’:
/tmp/.gyp/8.11.4/include/node/v8.h:813: error: ‘nullptr’ was not declared in this scope
/tmp/.gyp/8.11.4/include/node/v8.h: At global scope:
/tmp/.gyp/8.11.4/include/node/v8.h:839: error: expected unqualified-id before ‘using’
/tmp/.gyp/8.11.4/include/node/v8.h:1188: error: ‘nullptr’ was not declared in this scope
/tmp/.gyp/8.11.4/include/node/v8.h:1194: error: ‘nullptr’ was not declared in this scope
/tmp/.gyp/8.11.4/include/node/v8.h: In constructor ‘v8::RegisterState::RegisterState()’:
/tmp/.gyp/8.11.4/include/node/v8.h:1743: error: ‘nullptr’ was not declared in this scope
/tmp/.gyp/8.11.4/include/node/v8.h: At global scope:
/tmp/.gyp/8.11.4/include/node/v8.h:3213: error: ‘nullptr’ was not declared in this scope
/tmp/.gyp/8.11.4/include/node/v8.h: In member function ‘v8::MaybeLocal<v8::Object> v8::Function::NewInstance(v8::Local<v8::Context>) const’:
/tmp/.gyp/8.11.4/include/node/v8.h:3854: error: ‘nullptr’ was not declared in this scope
/tmp/.gyp/8.11.4/include/node/v8.h: At global scope:
/tmp/.gyp/8.11.4/include/node/v8.h:4123: error: function definition does not declare parameters
/tmp/.gyp/8.11.4/include/node/v8.h:4177: error: expected unqualified-id before ‘&’ token
/tmp/.gyp/8.11.4/include/node/v8.h:4177: error: expected ‘)’ before ‘&’ token
/tmp/.gyp/8.11.4/include/node/v8.h:4177: error: expected ‘;’ before ‘&’ token
In file included from /usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/ostream_insert.h:36,
                 from /usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/string:46,
                 from /usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/locale_classes.h:42,
                 from /usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/bits/ios_base.h:43,
                 from /usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/ios:43,
                 from /usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/ostream:40,
                 from /usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/iostream:40,
                 from ../src/fibers.cc:8:
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/cxxabi-forced.h:29: error: expected ‘;’ before end of line
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/cxxabi-forced.h:29: error: expected ‘}’ before end of line
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/cxxabi-forced.h:29: error: expected unqualified-id before end of line
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/cxxabi-forced.h:29: error: expected ‘}’ before end of line
/usr/lib/gcc/x86_64-redhat-linux/4.4.7/../../../../include/c++/4.4.7/cxxabi-forced.h:29: error: expected declaration before end of line
make: *** [Release/obj.target/fibers/src/fibers.o] Error 1
make: Leaving directory `/home/as2user/p4/main/apimcommon/ui/node_modules/fibers/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 2.6.32-642.el6.x86_64
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--release"
gyp ERR! cwd /home/as2user/p4/main/apimcommon/ui/node_modules/fibers
gyp ERR! node -v v8.11.4
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
node-gyp exited with code: 1
Please make sure you are using a supported platform and node version. If you
would like to compile fibers on this machine please make sure you have setup your
build environment--
Windows + OS X instructions here: https://github.com/nodejs/node-gyp
Ubuntu users please run: `sudo apt-get install g++ build-essential`
Alpine users please run: `sudo apk add python make g++`
sh: nodejs: command not found
npm WARN karma-sinon-chai@1.3.3 requires a peer of sinon-chai@^2.9.0 but none is installed. You must install peer dependencies yourself.
npm WARN sinon-chai@3.0.0 requires a peer of chai@^4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! fibers@1.0.15 install: `node build.js || nodejs build.js`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the fibers@1.0.15 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/as2user/.npm/_logs/2018-08-28T14_08_46_540Z-debug.log

**Comment by BorisOsipov** [comment]
It's not wdio-cucumber issue.
In the error log
```
Please make sure you are using a supported platform and node version. If you
would like to compile fibers on this machine please make sure you have setup your
build environment--
Windows + OS X instructions here: nodejs/node-gyp
Ubuntu users please run: sudo apt-get install g++ build-essential
Alpine users please run: sudo apk add python make g++
```
Or find how to install on Redhat in node-gyp docs.

**Comment by obender** [comment]
Yes but it's you using this fibers lib as your dependency

**Comment by christian-bromann** [comment]
You need `nodejs/node-gyp` to install Fibers which is a dependency of wdio-cucumber-framework. In v5 this is not required anymore but for v4 just make sure you support `node-gyp`

**Comment by obender** [comment]
I had managed to resolve it, i just removed gcc , using `sudo yum remove gcc`
