### ISSUE TITLE
Less information in afterStep - stepResult

### ISSUE THREAD

**Issue by woolter** [webdriverio/wdio-cucumber-framework#149]
Hi!

In 1.1.1 in afterStep in stepResult I get all this information:

`StepResult {
  attachments: [],
  duration: 1692,
  step:
   Step {
     arguments: [],
     line: 4,
     name: 'I open the url "https://www.google.com/"',
     scenario:
      Scenario {
        feature: [Object],
        keyword: 'Scenario',
        lines: [Array],
        name: 'GOOGLE',
        tags: [],
        uri: '/Users/walter.lijo/Documents/src/features/testSimple/search_ONE.feature',
        line: 3,
        description: undefined,
        steps: [Array] },
     uri: '/Users/walter.lijo/Documents/src/features/testSimple/search_ONE.feature',
     isBackground: false,
     keyword: 'Given ',
     keywordType: 'precondition' },
  stepDefinition:
   StepDefinition {
     code: [Function: arity3],
     line: 176,
     options: {},
     pattern: /^I open the (url|site) "([^"]*)?"(?: with uuid "([^"]*)?")*$/,
     uri: '/Users/walter.lijo/Documents/node_modules/wdio-cucumber-framework/node_modules/cucumber/lib/index.js' },
  status: 'passed' }`

But in 2.2.6 I only get this
`{ type: 'Step',
  location: { line: 4, column: 5 },
  keyword: 'Given ',
  text: 'I open the url "https://www.google.com/"',
  argument: undefined }`

The issue for me is that I use **stepResult.status** to take an screenshot on fail

**Comment by woolter** [comment]
@christian-bromann @BorisOsipov I was able to add more information to **stepResult** now locally i have this information:
`{ type: 'Step',
  location: { line: 4, column: 5 },
  keyword: 'Given ',
  text: 'I open the url "https://www.google.com/"',
  argument: undefined,
  feature: 'SEARCH TOOLS ONE',
  scenario: 'GOOGLE',
  status: 'passed' }`

Al least is all the information that I was using from the version 1.1.1, we can add more if we want, and the result still a JSON not like in the version 1.1.1

In the way that works today I'm not able to see the value

What do you think?
If you are ok, I make the PR

**Comment by woolter** [comment]
@christian-bromann done! https://github.com/webdriverio/wdio-cucumber-framework/pull/150

**Comment by BorisOsipov** [comment]
Fixed in https://github.com/webdriverio/wdio-cucumber-framework/pull/150
