### ISSUE TITLE
Can you get tags from configuration file in beforeScenario function

### ISSUE THREAD

**Issue by mareru** [webdriverio/wdio-cucumber-framework#156]
Hello,  
is there a way to get the tags from configuration file test.conf.js that are set in the attribute:
```
cucumberOpts: {
    tags: ['@registration', '~@WIP']
}
```
in function `beforeScenario`?

**Comment by christian-bromann** [comment]
Try `browser.config.cucumberOpts.tags`.

**Comment by mareru** [comment]
It was `browser.options.cucumberOpts.tags`. But thanks for the tip :)
