### ISSUE TITLE
Skipped scenarios - if one fails the rest got skipped 

### ISSUE THREAD

**Issue by AlinaVasylieva** [webdriverio/wdio-cucumber-framework#157]
Hey guys!
Currently faced the situation that if one of the scenarios fails the ongoing scenarios in the same feature file are skipped. 

Using:
"wdio-cucumber-framework": "^1.1.0",
 "webdriverio": "^4.13.2"

 I have looked through all possible documentation, but haven't found any solution, nor the proof that this kind of behaviour is normal, could you please advise? Have you faced this before?

**Comment by BorisOsipov** [comment]
>Have you faced this before?

no. Can you share some example repo on github? Also some logs how it looks like will be helpful

**Comment by AlinaVasylieva** [comment]
@BorisOsipov  I will try to prepare the example solution and provide log! Thanks for taking a look!

@woolter I have tried your versions - same situation with the slight difference!
Before setting up your versions statically if one scenario was failing the ongoing one was not even stated for execution, thus for example  as the result I see - 13 passed, 1 failed, 3 pending, even though, I have the ongoing scenario with 17 steps more.

![image](https://user-images.githubusercontent.com/19437831/50219652-345a0700-0390-11e9-9f96-2466af22ac49.png)
![image](https://user-images.githubusercontent.com/19437831/50219663-3a4fe800-0390-11e9-87b6-a8e7febc672c.png)


When I set your versions statically - my second scenario is still skipped, but now I see those steps as pending:
![image](https://user-images.githubusercontent.com/19437831/50219524-cb728f00-038f-11e9-8ea6-6745d1220663.png)
![image](https://user-images.githubusercontent.com/19437831/50219533-d62d2400-038f-11e9-9008-03e05cf2f782.png)
![image](https://user-images.githubusercontent.com/19437831/50219539-df1df580-038f-11e9-851a-c1c7639c2f42.png)

What I'm trying to understand if the second scenario should be executed? Or I need any specific configuration?

**Comment by woolter** [comment]
> What I'm trying to understand if the second scenario should be executed by default? Or I need any specific configuration?

Yes the second scenario should be executed by default

@AlinaVasylieva  can you share your cucumberOpts?
```json
cucumberOpts: {
    "require": ["./src/support/setup.js", "./src/step_definitions/*"],
    "backtrace": false,
    "compiler": ["js:babel-register"],
    "dryRun": false,
    "failFast": false,
    "format": ["pretty"],
    "colors": true,
    "snippets": true,
    "source": true,
    "profile": [],
    "strict": false,
    "tags": "",
    "timeout": 1000,
    "ignoreUndefinedDefinitions": false,
  },
```

**Comment by AlinaVasylieva** [comment]
@woolter 
Here're mine:

```
cucumberOpts: {
    require: ['./src/steps/*'],
    backtrace: true,  
    compiler: [ 'js:babel-register'],
    dryRun: false,      
    failFast: true,    
    format: ['summary'],
    colors: true,      
    snippets: true,     
    source: true,       
    profile: [],        
    strict: true,     
    tagsInTitle: true,
    tags: [],          
    timeout: 60000,    
    ignoreUndefinedDefinitions: false, 
  },
```

**Comment by BorisOsipov** [comment]
@AlinaVasylieva set `failFast: false` and try again.

**Comment by AlinaVasylieva** [comment]
@BorisOsipov worked! Thank you s much guys for your help!
@woolter

**Comment by BorisOsipov** [comment]
Ok close then
