### ISSUE TITLE
cucumberOpts 'format' not working

### ISSUE THREAD

**Issue by arif49** [webdriverio/wdio-cucumber-framework#16]
I want to use the 'format' option while I run wdio-cucumber. But I cant figure out  how to make this work, lets say I want to write output from cucumber js into a json file.

```
cucumberOpts: {
   failFast: false,
   timeout: 20000,
   snippets: false,
   backtrace: true,
   format: ['json:report/out.json']
}
```

I want to generate my report as cucumber js format as the default 'dot' or 'json' reporter is not a option for me to print pretty cucumber test results

**Comment by snehatulsi** [comment]
hi. did you find a solution for using reporter inside this framework

**Comment by arif49** [comment]
Sorry no luck! I have ended up writing a custom reporter to display results in a friendly manner. See the below explanation, 

https://github.com/webdriverio/wdio-cucumber-framework/issues/6
