### ISSUE TITLE
When will wdio-cucumber-framework migrate wdio V4 to V5?

### ISSUE THREAD

**Issue by espekkaya** [webdriverio/wdio-cucumber-framework#168]
Hello,
I want to use wdio V5 insted of v4. Is there any progress to migrate wdio V4 to V5?

Thank you in advance.

**Comment by christian-bromann** [comment]
@espekkaya yes, there is a PR https://github.com/webdriverio/webdriverio/pull/3667 .. if you have interest in this, please get involved.
