### ISSUE TITLE
Question: How do you use the build in Reporter?

### ISSUE THREAD

**Issue by de-robat** [webdriverio/wdio-cucumber-framework#174]
First of all, thanks for this framework. It works really well. Im just having trouble to figure out, how i am supposed to use the reporter. I can see it doing its work, in terms of sending events via process.send out of the cucumber framework, but i cant get any wdio reporter to pick up on these events. they just dont get passed trough the process chain.

So neither the spec nor the dot reporter do anything for me when running my tests. Sorry if the answer is obvious, but i spend to many hours already trying to get it to work so i figured i give it a try and just ask :D

the relevant versions are:

"@wdio/local-runner": "^5.10.4",
"@wdio/spec-reporter": "^5.9.3",
"cucumber": "^5.1.0",
"wdio-cucumber-framework": "^2.2.8",
"webdriverio": "^5.10.4"

update:

just saw
```
The wdio runner currently supports Mocha and Jasmine and Cucumber (not yet supported in v5)
```
in the wdio docs. is this eventually my issue?

**Comment by BorisOsipov** [comment]
>Cucumber (not yet supported in v5)

yes, you still can't use cucumber with v5.

You can speed up cucumber support by contributing to the PR https://github.com/webdriverio/webdriverio/pull/3667

**Comment by de-robat** [comment]
Ty for the quick response, i was wondering if this note is up to date becaues evrything else seems to work just fine already. So thank for saving my sanity by confirming!

**Comment by jlin-namely** [comment]
@de-robat did u say that it is working for you?

**Comment by de-robat** [comment]
Well so far, ive written step bindings, some specs in gherkin, but cant get the reproter to work. so yes the version i have do work togehter. but i may not have used alle the features of cucumber/wdio yet. but so far no issues besides the reporter obv. is there a list that shows the parts that are still open to be ported @jlin-namely ?
