### ISSUE TITLE
Default timeout in README does not match default timeout in adapter.js

### ISSUE THREAD

**Issue by timbru31** [webdriverio/wdio-cucumber-framework#21]
README says it's 10000 https://github.com/webdriverio/wdio-cucumber-framework#timeout

Code says it's 30000 https://github.com/webdriverio/wdio-cucumber-framework/blob/master/lib/adapter.js#L12

I'm happy to make a PR - which of the values is the correct one?

**Comment by christian-bromann** [comment]
There is no "right" value. I think 30s is fine though.
