### ISSUE TITLE
strict mode setting of cucumber is ignored

### ISSUE THREAD

**Issue by timbru31** [webdriverio/wdio-cucumber-framework#26]
**Problem**
The wdio-cucumber-framework does pass the strict option (true/false), but ignores the result. This happens due to the fact that cucumber handles each individual step result regardless of the strict mode setting, but in the end determines the feature result and checks for the strict mode option.

You can see it here in the cucumber project:
https://github.com/cucumber/cucumber-js/blob/master/lib/cucumber/runtime/features_runner.js#L6
https://github.com/cucumber/cucumber-js/blob/master/lib/cucumber/runtime/features_result.js#L22

**Suggestion**
The reporter should check for the strict mode option and overwrite the step result in case the step is undefined or skipped/pending to `fail`

**Comment by christian-bromann** [comment]
PRs welcome

**Comment by christian-bromann** [comment]
@timbru31 is this still a valid issue with latest cucumber-js?

**Comment by timbru31** [comment]
I can't answer this question, since I'm not using cucumber-js currently.

**Comment by christian-bromann** [comment]
ok, let's close this then. Happy to reopen if someone has the same issue with the latest updates.
