### ISSUE TITLE
v0.2.3 Loops test when callback is called

### ISSUE THREAD

**Issue by sameer-b** [webdriverio/wdio-cucumber-framework#29]
For some reason when I call the callback() at the end of my test it restarts my test. And keeps looping over my first test.

Any idea why this behavior?
I'm using wdio sync, w/ `sync=true` and my steps are `sync-my-step.js`

**Comment by christian-bromann** [comment]
you don't need to call the callback then

**Comment by sameer-b** [comment]
Okay I will test this out and report back/close the issue.

**Comment by sameer-b** [comment]
I tested it out my suite hangs on the first test. It will not proceed to the next step. :s
Can you reopen the issue?

**Comment by christian-bromann** [comment]
Can you show your step definitions? There is no need to use the callback method in webdriverio since all commands are sync anyway

**Comment by sameer-b** [comment]
Your new release 0.2.4 fixed the issue. :)
Thanks

**Comment by christian-bromann** [comment]
Nice, yeah I think `v0.2.3` was a buggy release anyway
