### ISSUE TITLE
All tests marked as pending on first pending step

### ISSUE THREAD

**Issue by sameer-b** [webdriverio/wdio-cucumber-framework#30]
I have steps in the following order
- Step 1 (done)
- Step 2 (pending)
- Step 3 (done)

After Step 2 even Step 3 is marked as pending. 
I have 

```
{
    failFast: false
    ignoreUndefinedDefinitions: true,
    failAmbiguousDefinitions: false
}
```

**Comment by christian-bromann** [comment]
How did you skip a single test?

**Comment by sameer-b** [comment]
By skip I meant pending. (The feature is not implemented yet).
