### ISSUE TITLE
Commands like waitForVisible not working anymore

### ISSUE THREAD

**Issue by arif49** [webdriverio/wdio-cucumber-framework#31]
With the updated module (v0.2.4), if I ran command like he following it gives me weird output thats makes no sense.. I am assuming the module is broken for `wait` related commands. My be because of updated cucumber dependency?

```
var myElem = browser.element('#myElem');
myElem.waitForVisible();
```

**Output:**

```
2) Get title of website should the title of the page be "GitHub · Where software is built":
undefined
running phantomjs
undefined
```

**Comment by christian-bromann** [comment]
Please try again with latest version.
