### ISSUE TITLE
How to use --cucumberOpts.name

### ISSUE THREAD

**Issue by pscheit** [webdriverio/wdio-cucumber-framework#33]
Hi there,

I cant get the name-option  to work.

if I put into my config:

```
    cucumberOpts: {
        name: ['Viewing all teams on the homepage'],
   }
```

it does work.

But when I apply this from the command line:

```
wdio --cucumberOpts.name="Viewing all teams on the homepage"
```

the value is a string. But `Cucumber.Cli.Configuration` needs to have an array. I can specify the `--cucumberOpts.name` twice, but thats an ugly workaround, isn't it?

best regards
Philipp

**Comment by wvankuipers** [comment]
You can specify an array of options separating them by a `,` like so:

    wdio --cucumberOpts.name="Viewing all teams","on the homepage"

**Comment by christian-bromann** [comment]
thanks @wvankuipers
