### ISSUE TITLE
npm install wdio-cucumber-framework --save-dev not working on windows 7 64 bit

### ISSUE THREAD

**Issue by prasanjitmohanty** [webdriverio/wdio-cucumber-framework#39]
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install" "wdio-cucumber-framework" "--save-
dev"
npm ERR! node v5.5.0
npm ERR! npm  v3.3.12
npm ERR! code ELIFECYCLE

npm ERR! fibers@1.0.15 install: `node build.js || nodejs build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the fibers@1.0.15 install script 'node build.js || nodejs bui
ld.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the fibers package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node build.js || nodejs build.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls fibers
npm ERR! There is likely additional logging output above.

**Comment by christian-bromann** [comment]
Seems that fibers failed to install, please file an issue in this project: https://github.com/laverdet/node-fibers

**Comment by megamindbrian** [comment]
Why do you need to use fibers in wdio?  I am getting this error too.

**Comment by christian-bromann** [comment]
@megamindbrian fibers makes all commands synchronous and nice to use
