### ISSUE TITLE
WDIO and Cucumberjs 0.9

### ISSUE THREAD

**Issue by teneightfive** [webdriverio/wdio-cucumber-framework#4]
I've been trying to upgrade my webdriver testrunner setup to cucumber 0.9.2 but am hitting a lot of issues. 

I notice your package is now using the latest version of cucumber though. I was previously using webdriver 3.2.4 with cucumber 0.5.3. Upgrading webdriver to 3.4.0 worked fine so I tried upgrading cucumber. 

It works with my current setup back to cucumber 0.7.0. v0.8.1 seems to hang on step definitions and upgrading to 0.9.2 fails when trying to run cucumber cli. I get the following:
```
ERROR: Cannot read property 'length' of undefined
Type    at Function.Configuration [project_dir]/node_modules/cucumber/lib/cucumber/cli/configuration.js:8:11)
```

I've even tried stripping my config right back to a very basic setup but it still fails...any idea on how to solve this?

**Comment by christian-bromann** [comment]
Hi,
This package only works with the new webdriverio v4. We haven't it released it yet but are about to do so really soon!

**Comment by christian-bromann** [comment]
For now please stick with the old cucumber version

**Comment by teneightfive** [comment]
Ah right. That would make sense. 

Thanks. I'll keep my eye out for webdriverio v4...
