### ISSUE TITLE
Does not work with new cucumber release

### ISSUE THREAD

**Issue by lj9142** [webdriverio/wdio-cucumber-framework#41]
Hello,

I have updated my version of cucumber to 2.0.0 as it was released 4 days ago and it does not seem to be compatible with my framework as i am getting the following error:

![image](https://cloud.githubusercontent.com/assets/22213596/20715279/963d6276-b646-11e6-8ac5-22fbd03e176d.png)

I don't know if this is a direct cucumber issue or if it is just no longer compatible with this wdio module.

I have the workaround of going back to the old version but can you advise if i have raised this in the right place? I havent seen any similar bugs here or in the cucumber-js repository.

Thank you!

**Comment by christian-bromann** [comment]
As it states in the [package.json](https://github.com/webdriverio/wdio-cucumber-framework/blob/master/package.json#L60-L62), right now only 1.x is supported. We will update Cucumber with the next release.
