### ISSUE TITLE
Output is incomplete

### ISSUE THREAD

**Issue by rochdev** [webdriverio/wdio-cucumber-framework#46]
Given a feature:

```gherkin
Feature: My Feature
    Scenario: My Scenario
        Given some context
        When I do something
        Then I achieve some goal
```

I would expect to have a similar output in the console, but instead I get:

```
My Feature

My Scenario
    ✓ some context
    ✓ I do something
    ✓ I achieve some goal
```

It's missing all the keywords to make proper sentences which are usually added by cucumber.

I am using the `spec` reporter with the `pretty` formatter.

**Comment by christian-bromann** [comment]
@rochdev right now this is how spec reporter works. It isn't quite aligned to other cucumber reporters. Note that WebdriverIO has framework independent reporters that work also with other test frameworks like Mocha or Jasmine.

The spec reporter could be smarter about which framework is used and adapt the output accordingly.

**Comment by christian-bromann** [comment]
This issue was moved to webdriverio/wdio-spec-reporter#21
