### ISSUE TITLE
Is there a way for the JSON reporter output to include the Gherkin step (i.e. Given, When , Then)?

### ISSUE THREAD

**Issue by BrandonDBrown** [webdriverio/wdio-cucumber-framework#50]
I would like the JSON output to include the Given When and Then steps. Is there a way this can be added to the JSON reporter when Cucumber is being used? If not, is there a way to add this to a custom reporter?

**Comment by christian-bromann** [comment]
@BrandonDBrown sure this can be added to the json reporter. Just do a PR 😉 . The reporter is not owned by us but I am sure @fijijavis won't have anything against it.

**Comment by BrandonDBrown** [comment]
@christian-bromann Great idea! Part of my question was asking for some help on how to add this to a custom reporter. If you have any ideas?

**Comment by christian-bromann** [comment]
> If you have any ideas?

Just look how the json reporter is implemented and integrate the customer reporter like in here: https://github.com/webdriverio/webdriverio/blob/master/examples/wdio/wdio.customreporter.conf.js

**Comment by BrandonDBrown** [comment]
@christian-bromann Bingo. I have done all this, but I don't know how to access the Given, Then and When keywords to add to my custom reporter.  Sorry my initial question wasn't very detailed.

**Comment by christian-bromann** [comment]
If you don't get the data via the event payloads we need to enhance the wdio-cucumber-framework do send that data

**Comment by BrandonDBrown** [comment]
Right now I am not seeing the data in the event payload. Wasn't sure if I was missing something.

**Comment by christian-bromann** [comment]
> Wasn't sure if I was missing something.

as I said then we need to enhance the [reporter](https://github.com/webdriverio/wdio-cucumber-framework/blob/master/lib/reporter.js) to send the step name

**Comment by osmolyar** [comment]
@BrandonDBrown , were you able to create a custom json wdio reporter for cucumber that would at least roll up the status of each Scenario based on the states of its steps ('tests', according to the default json reporter)?
