### ISSUE TITLE
Cannot OR tags when providing them through CLI

### ISSUE THREAD

**Issue by Kignuf** [webdriverio/wdio-cucumber-framework#53]
Hello
I'm unable to ask cucumber to run features that have @tag1 OR @tag2 when providing the tags through CLI.

It seems that the tags I give are always split using the coma, which translates into AND for cucumber.

So the following
```sh
$ wdio wdio.conf.js --cucumberOpts.tags="@ios,@android"
```

Is strictly equivalent to
```sh
$ wdio wdio.conf.js --cucumberOpts.tags="@ios","@android"
```

When I print the config.cucumberOpts.tags object, in both cases I get
['@ios', '@android']

According to the doc, it should not be equivalent and first example should apply a logical OR, which translates in the following value:
```js
config.cucumberOpts.tags = ['@ios,@android']
```

I hope that's clear enough. If not, please let me know.

**Comment by Kignuf** [comment]
Hello,
I've just tested it in cucumber js (using the [TuteCumber tutorial](https://github.com/denford/TuteCumber)) and it does work, but the way you do the AND is different

OR
```
$ cucumber --tags=@tag1,@tag2
```

AND
```
$ cucumber --tags=@tag1 --tags=@tag2
```


This won't work for wdio, an exception is thrown
```
$ wdio --cucumberOpts.tags=@ios --cucumberOpts.tags=@android
```
-->
```
node_modules/webdriverio/build/lib/cli.js:312
        argv.cucumberOpts.tags = argv.cucumberOpts.tags.split(',');

TypeError: argv.cucumberOpts.tags.split is not a function
```

**Comment by christian-bromann** [comment]
This can be fixed in `cli.js`

**Comment by Kignuf** [comment]
Got it, I'll try to have a look tomorrow, thanks Christian.
