### ISSUE TITLE
When running cucumber tests with webdriverio not getting code snippets as how Cucumberjs splits on console

### ISSUE THREAD

**Issue by rameshrengasamy** [webdriverio/wdio-cucumber-framework#56]
Not sure if its not possible currently or if im doing something wrong. 
I really liked how webdriverio works compared to selenium-webdriver. Im trying to use cucumberjs with webdriverio. I created a sample feature file and no step definitions. When i run using webdriverio config it just says as below but does not split the code skeleton snippets to console just how cucumberjs does. Could you help me if i had to set any flag for that?

1) Performing a search12 I am on the search page:
Step "I am on the search page" is not defined. You can ignore this error by setting
                              cucumberOpts.ignoreUndefinedDefinitions as true.
running chrome

**Comment by christian-bromann** [comment]
@rameshrengasamy I am afraid we don't get this information in WebdriverIO from cucumber so we can't display it :-/.
