### ISSUE TITLE
webdriverio with cucumber - code snippet for undefined steps not printing to console

### ISSUE THREAD

**Issue by rameshrengasamy** [webdriverio/wdio-cucumber-framework#57]
@christian-bromann First of all, I m sorry to bring up this back. Couldnt reopen the older issue. I know you replied to this in the other issue i created #56
But just thought to understand/get clear. Sorry again on first place. 
So i see protractor cucumber framework (https://www.npmjs.com/package/protractor-cucumber-framework) does print the snippets to the console. So it must be getting that from cucumber in some way right? 
When i run the cucumber tests with protractor, when there are no steps defined it prints as below in the console.

![image](https://cloud.githubusercontent.com/assets/8825324/25970493/e185381c-3666-11e7-8979-c9321666b16e.png)

But when i run similar test with wdio-cucumber-framework, i get the below in console -->

![image](https://cloud.githubusercontent.com/assets/8825324/25970634/56b1ea5e-3667-11e7-9bd8-7113542d73c2.png)

It doesnt display the snippets for undefined steps. 

This would be a useful feature as someone new to the framework can use this skeleton to build tests.

Is this something still could be added as a functionality or do i have to set any flag or this is out of scope for wdio-cucumber-framework?

**Comment by christian-bromann** [comment]
It is definitely useful so PRs welcome

**Comment by johanvaniperen** [comment]
I added a reporter for this, wdio-cucumber-snippet-reporter.
So, if you want to take a look. That 'll be nice :-)

**Comment by christian-bromann** [comment]
Awesome 👍
