### ISSUE TITLE
cucumber format with a path not working?

### ISSUE THREAD

**Issue by ricoli** [webdriverio/wdio-cucumber-framework#6]
Hello, I'm trying to have cucumber output a json report using the format configuration key. Features run fine, but nothing gets written to the specified file:

```
    cucumberOpts: {
...
        format: ['pretty', 'json:bdd-report.json'], // <string[]> (type[:path]) specify the output format, optionally supply PATH to redirect formatter output (repeatable)
...
    },
```

Any clues?

**Comment by christian-bromann** [comment]
We overwrite the reporter in the adapter so this property actually doesn't do anything. I don't know if it makes much sense to allow cucumber reporting since WebdriverIO has its own reporter tools that are especially designed for concurrent test suites.

We should remove this option in the description though.

**Comment by ricoli** [comment]
Ah thank you for explaining... Would there be a way to get the json report at this point in time though?

**Comment by christian-bromann** [comment]
> Would there be a way to get the json report at this point in time though?

No, you can tweak the compiled framework code though

**Comment by twKrash** [comment]
We need json report to generate cucumber-html-report (from here https://github.com/leinonen/cucumber-html-report ). Any thought how we can do this ?

**Comment by IGZangelsanchez** [comment]
I need the cucumber json output to send from a CI server to a external service that parses the JSON.
The WebdriverIO reporters are ok, but sometimes we need the original cucumber output.
If we can get the cucumber json ouput, It will be fantastic.

I wrote a ugly workaround to achieve this (it was written in a few minutes could be improved):

1- in wdio.conf.js
```
onPrepare: function (config, capabilities) {
    const resultsJsonLocation = path.join(__dirname, 'tests_result.json')
    if (fs.existsSync(resultsJsonLocation)) {
      fs.unlinkSync(resultsJsonLocation)
    }
  },
```

2- a cucumber hook to write the json file or append if exists (test/acceptance/step_definitions/support/jsonOutput.js):
```
const path = require('path')
var Cucumber = require('cucumber')
var JsonFormatter = Cucumber.Listener.JsonFormatter()
var fs = require('fs')

module.exports = function JsonOutputHook () {
  JsonFormatter.log = function (resultString) {
    const jsonFileLocation = path.join(__dirname, '../../../../tests_result.json')

    if (fs.existsSync(jsonFileLocation)) {
      const allResults = JSON.parse(fs.readFileSync(jsonFileLocation).toString())
      allResults.push(JSON.parse(resultString)[0])
      fs.writeFileSync(jsonFileLocation, JSON.stringify(allResults))
    } else {
      fs.writeFileSync(jsonFileLocation, resultString)
    }
  }

  this.registerListener(JsonFormatter)
}
```

**Comment by royriojas** [comment]
Hi @christian-bromann, I know this issue has some time and there seems to be an existing workaround, but I will like to point that cucumber seems to accept multiple reporters, maybe you guys want to reconsider just honor the `format` property? I tested the following code in my fork on the `adapter.js` file and it just worked. Would you guys be open to accept a PR for this functionality?

```javascript
var formatters = cucumberConf.getFormatters();
formatters.forEach(function (formatter) {
    runtime.attachListener(formatter);
});
```

just after this line 
https://github.com/webdriverio/wdio-cucumber-framework/blob/master/lib/adapter.js#L60

with these 3 lines the reporters in webdriver continue to work normally

**Comment by christian-bromann** [comment]
Thanks for all the downvotes 👍  😆 

The decision to block cucumber reporters was intentional. These reporters only work when running feature specs synchronously one after each other. This is different when running Selenium tests. Since they take longer than unit test you want to run them in parallel. All reporter output becomes nonsense then, here is an example by just running one feature with 3 browser:

```

Feature: Example feature

    As a user of WebdriverIO
    I should be able to use different commands
    to get informations about elements on the page

Feature: Example feature

    As a user of WebdriverIO
    I should be able to use different commands
    to get informations about elements on the page

  Scenario: Get size of an element
  Scenario: Get size of an element
Feature: Example feature

    As a user of WebdriverIO
    I should be able to use different commands
    to get informations about elements on the page

  Scenario: Get size of an element
  ✔ Given I go on the website "https://google.com/"
  ✔ Given I go on the website "https://google.com/"
․․  ✔ Given I go on the website "https://google.com/"
․  ✔ Then should the element "#gb_70" be 74px wide and 29px high
․
  Scenario: Get title of website
  ✔ Then should the element "#gb_70" be 74px wide and 29px high
․  ✔ Then should the element "#gb_70" be 74px wide and 29px high
․

  Scenario: Get title of website
  Scenario: Get title of website
  ✔ Given I go on the website "https://google.com/"
․  ✔ Given I go on the website "https://google.com/"
․  ✔ Then should the title of the page be "Google"
․  ✔ Given I go on the website "https://google.com/"
․
2 scenarios (2 passed)
4 steps (4 passed)
0m04.090s
  ✔ Then should the title of the page be "Google"
․
2 scenarios (2 passed)
4 steps (4 passed)
0m03.937s
  ✔ Then should the title of the page be "Google"
․
2 scenarios (2 passed)
4 steps (4 passed)
0m03.822s
```

Looks pretty right? You don't know which browser ran which feature so if there is an error you don't know which browser has caused it. The same would happen with cucumbers json reporter. It would just overwrite the json reports.

WebdriverIO provides a bunch of reporters these days: dot, spec, tap, junit, allure (which is an html reporter), teamcity, json, concise. These reporters take into consideration the fact that tests run concurrently. Here is an example on how the spec reporter would look like running the same test:

```
------------------------------------------------------------------
[phantomjs #2-0] Session ID: 89597bf3-58a0-4b76-9324-71ed3d705895
[phantomjs #2-0] Spec: /Users/christianbromann/Sites/Webprojekte/webdriverjs/DEV/examples/wdio/runner-specs/cucumber/features/my-feature.feature
[phantomjs #2-0] Running: phantomjs
[phantomjs #2-0]
[phantomjs #2-0]   Example feature
[phantomjs #2-0]
[phantomjs #2-0]   Get size of an element
[phantomjs #2-0]       ✓ I go on the website "https://google.com/"
[phantomjs #2-0]
[phantomjs #2-0]   Get title of website
[phantomjs #2-0]       ✓ I go on the website "https://google.com/"
[phantomjs #2-0]       ✓ should the title of the page be "Google"
[phantomjs #2-0]
[phantomjs #2-0]
[phantomjs #2-0] 3 passing (7s)
[phantomjs #2-0]

------------------------------------------------------------------
[chrome #0-0] Session ID: 3802171a-e05a-4f37-9d04-f272789f33f4
[chrome #0-0] Spec: /Users/christianbromann/Sites/Webprojekte/webdriverjs/DEV/examples/wdio/runner-specs/cucumber/features/my-feature.feature
[chrome #0-0] Running: chrome
[chrome #0-0]
[chrome #0-0]   Example feature
[chrome #0-0]
[chrome #0-0]   Get size of an element
[chrome #0-0]       ✓ I go on the website "https://google.com/"
[chrome #0-0]
[chrome #0-0]   Get title of website
[chrome #0-0]       ✓ I go on the website "https://google.com/"
[chrome #0-0]       ✓ should the title of the page be "Google"
[chrome #0-0]
[chrome #0-0]
[chrome #0-0] 3 passing (9s)
[chrome #0-0]

------------------------------------------------------------------
[firefox #1-0] Session ID: ad6941a9-954d-4fc9-b0b2-16f268a784f8
[firefox #1-0] Spec: /Users/christianbromann/Sites/Webprojekte/webdriverjs/DEV/examples/wdio/runner-specs/cucumber/features/my-feature.feature
[firefox #1-0] Running: firefox
[firefox #1-0]
[firefox #1-0]   Example feature
[firefox #1-0]
[firefox #1-0]   Get size of an element
[firefox #1-0]       ✓ I go on the website "https://google.com/"
[firefox #1-0]
[firefox #1-0]   Get title of website
[firefox #1-0]       ✓ I go on the website "https://google.com/"
[firefox #1-0]       ✓ should the title of the page be "Google"
[firefox #1-0]
[firefox #1-0]
[firefox #1-0] 3 passing (10s)
[firefox #1-0]
```

I think there is no need to have support for cucumber backed reporters. Especially since they are useless in the context of integration testing. Thanks for understanding.

**Comment by damonpam** [comment]
Is there any option in wdio to display the usage of step definitions similiar as the cucumber formatter `usage`?
