### ISSUE TITLE
Possible to have steps not have to specify element vs inputfield?

### ISSUE THREAD

**Issue by cheapsteak** [webdriverio/wdio-cucumber-framework#61]
It seems unnecessary as whether the element is an inputfield should be inferable via an element's tagName

Unless I'm missing a caveat or edgecases

**Comment by christian-bromann** [comment]
I don't understand your issue? What does this has to do with the framework adapter?

**Comment by cheapsteak** [comment]
omg I'm so sorry, I posted to the wrong repo
Should have posted to https://github.com/webdriverio/cucumber-boilerplate
