### ISSUE TITLE
Outdated build files 

### ISSUE THREAD

**Issue by skadeglad** [webdriverio/wdio-cucumber-framework#62]
Hello!

latest release solved `undefined error for reporting ` but `./build` folder in a package installed via `npm install wdio-cucumber-framework@0.3.1` still contains old build files, e.g.:

```
var err = stepResult.getFailureException();
    error = {
        message: err.message,
        stack: err.stack
    };
    this.failedCount++;
```
instead of:
```
var err = stepResult.getFailureException();
    if (err instanceof Error) {
        error = {
            message: err.message,
            stack: err.stack
        };
    } else {
        error = {
            message: err
        };
    }
    this.failedCount++;
```
inside `./build/reporter.js`

for now we need to manually build new version from `./lib` that is up-to-date

updating `./build` folder on npm would be much appreciated!

**Comment by okrajni** [comment]
+1

**Comment by SkadeGlad** [comment]
any chance for this being updated before `wdio-cucumber-framework@1.0.0` ?
