### ISSUE TITLE
rerun failed scenarios

### ISSUE THREAD

**Issue by aloksukhwal** [webdriverio/wdio-cucumber-framework#64]
I am using wdio-cucumber-framework for our project and want capability to re-run the failed scenarios completely instead of just re-trying the failed steps. Is there a way to do it? I have tried using cucumber option 'rerun' in webdriverio config, but it doesn't generate any rerun file.

Does this framework support it?
If yes, how to use it? 
If not, is anyone working on it? If not, I can try to look into it.

Please let me know. Thanks

**Comment by christian-bromann** [comment]
> Does this framework support it?

Atm only retrying steps is possible

> If not, is anyone working on it?

Not sure, don't think so

> If not, I can try to look into it.

That would be awesome! We are about to upgrade to Cucumber v2 so make sure it works with that version.

Also join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) for such question. This is not necessary an issue.

**Comment by deepikadixitb** [comment]
Is there any update on this issue?
