### ISSUE TITLE
Compiler option (e.g. Babel) not working since v1.0.0

### ISSUE THREAD

**Issue by colinrotherham** [webdriverio/wdio-cucumber-framework#70]
Thanks for the *v1.0.0* update.

Unfortunately my required files are no longer being processed by Babel
i.e. `ERROR: Unexpected token import`

These options work in *v0.3.1* but not in *v1.0.0*.

```js
cucumberOpts: {
    compiler: [
        'js:babel-core/register'
    ],
    require: [
        './path/to/steps/example.js'
    ]
}
```

Have there been any breaking config changes?

**Comment by colinrotherham** [comment]
Under *v0.3.1* both `js:babel-register` and `js:babel-core/register` work as the compiler option.

**Comment by lgandecki** [comment]
I think there is a PR for that, we will merge soon

**Comment by christian-bromann** [comment]
see #72

**Comment by SchwaFa** [comment]
We still get the error `ERROR: Unexpected token` import using _v1.0.2_ using

```
compiler: [
        'js:babel-core/register'
    ]
```

So has this really been fixed already??

**Comment by colinrotherham** [comment]
@SchwaFa Are you on one of the newer Babel v7 betas?

They've changed `babel-register` to `@babel/register`.

Try this:

```js
compiler: ['js:@babel/register']
```

**Comment by SchwaFa** [comment]
@colinrotherham No, we are not using Babel v7, still on 6.26

**Comment by colinrotherham** [comment]
If you run `babel-register` manually and *require()* one of your files do you still get `ERROR: Unexpected token import`?

You'll need to work out if this is your Babel set up or `wdio-cucumber-framework`.

**Comment by SchwaFa** [comment]
@colinrotherham It works fine when I manually run `babel-register`. So it seems to be a problem with the framework

**Comment by hackeryarn** [comment]
@colinrotherham thanks for the link it seems to be a problem with `babel` 6 and the newest version of this framework. I am able to run the starter you linkd.
