### ISSUE TITLE
Require documentation incorrect since v1.0.0

### ISSUE THREAD

**Issue by colinrotherham** [webdriverio/wdio-cucumber-framework#71]
Referring to the documentation here:
https://github.com/webdriverio/wdio-cucumber-framework#require

It suggests I can require entire directories like this:

```js
    require: [
        './path/to/steps'
    ]
```

This works fine in *v0.3.1*.

But in *v1.0.0* it looks like Node's module resolution is now used, so the require paths have to be exact filenames or directories with an `index.js` or `package.json` file.

E.g.

```js
    require: [
        './path/to/steps/example.js'
    ]
```

Shall I open a pull request to fix the documentation or is this a bug?

**Comment by lgandecki** [comment]
it's more of a lack of a feature I'd say, feel free to create a PR

**Comment by colinrotherham** [comment]
Thanks for adding https://github.com/webdriverio/wdio-cucumber-framework/commit/562d2a37b841120ca9b9eeda4b8ac83c465f2b7a 👍
