### ISSUE TITLE
Allow specifying which scenario to run by line number

### ISSUE THREAD

**Issue by AdenFlorian** [webdriverio/wdio-cucumber-framework#78]
Cucumberjs allows specifying a specific scenario to run by giving it the path to a feature file and the line number that the scenario is on: https://github.com/cucumber/cucumber-js/blob/master/docs/cli.md

`$ cucumber.js features/my_feature.feature:3`

Would be nice if this framework had a cucumber option for specifying the line number.

This is helpful for setting up an IDE to run just the scenario that the cursor is on.

**Comment by christian-bromann** [comment]
Fixed by webdriverio/webdriverio#3019

**Comment by mvgiacomello** [comment]
Anyone found a solution for this when running Mocha instead of Cucumber?

**Comment by jcollum-autodesk** [comment]
@christian-bromann I think that fix only applies to cucumber. It would be better (and more in line with other nodejs testing frameworks) if we could specify a test by name. When I try to run a single test using the proposed solution with wdio/mocha I get this: 

```
yarn test --spec e2e-test/specs/desktop/flows/project/project.spec.js:71
yarn run v1.17.3
$ yarn test-chrome --spec e2e-test/specs/desktop/flows/project/project.spec.js:71
$ wdio wdio/chrome.conf.js --spec e2e-test/specs/desktop/flows/project/project.spec.js:71
/Users/collumj/Documents/work/xyz/e2e-test/node_modules/@wdio/config/build/lib/ConfigParser.js:177
      throw new Error(`spec file(s) ${cliArgFileList.join(', ')} not found`);
      ^

Error: spec file(s) e2e-test/specs/desktop/flows/project/project.spec.js:71 not found
```

**Comment by erwinheitzman** [comment]
If you check the documentation about the spec option it states that it should be an array instead of a string: https://webdriver.io/docs/clioptions.html

Notice the error stating: cliArgFileList.join(', ')

**Comment by jcollum-autodesk** [comment]
How do I pass an array? The docs don't talk about it. 

```
yarn test --spec {e2e-test/specs/desktop/flows/project/project.spec.js:71}

yarn test --spec [e2e-test/specs/desktop/flows/project/project.spec.js:71]

yarn test --spec (e2e-test/specs/desktop/flows/project/project.spec.js:71)

```

None of those work. Plus, it's only one file, why would I need to put it in an array? Don't you think it's more likely that the CLI is thinking that `:71` is part of the file path? 

Actually now I question whether your docs are correct: 

    --version             prints WebdriverIO version                     [boolean]

`--version` expects a boolean, according to what you said above. But that makes zero sense.

**Comment by jcollum-autodesk** [comment]
OK I tried spaces, got the same error: 

    yarn test --spec e2e-test/specs/desktop/flows/project/project.spec.js:49 e2e-test/specs/desktop/flows/project/project.spec.js:70

```
/Users/collumj/Documents/work/xyz/e2e-test/node_modules/@wdio/config/build/lib/ConfigParser.js:177
      throw new Error(`spec file(s) ${cliArgFileList.join(', ')} not found`);
      ^

Error: spec file(s) e2e-test/specs/desktop/flows/project/project.spec.js:49, e2e-test/specs/desktop/flows/project/project.spec.js:70 not found
    at ConfigParser.setFilePathToFilterOptions (/Users/collumj/Documents/work/xyz/e2e-test/node_modules/@wdio/config/build/lib/ConfigParser.js:177:13)
    at ConfigParser.merge (/Users/collumj/Documents/work/xyz/e2e-test/node_modules/@wdio/config/build/lib/ConfigParser.js:79:37)
    at new Launcher (/Users/collumj/Documents/work/xyz/e2e-test/node_modules/@wdio/cli/build/launcher.js:34:23)
    at launch (/Users/collumj/Documents/work/xyz/e2e-test/node_modules/@wdio/cli/build/run.js:63:20)
```

The error makes sense: it can't find a file called `e2e-test/specs/desktop/flows/project/project.spec.js:49` because it is not clipping off the `:49` before loading the file.
