### ISSUE TITLE
Test runner, opens empty browser for each feature file with no tests targeted

### ISSUE THREAD

**Issue by AndrewKeig** [webdriverio/wdio-cucumber-framework#8]
## Problem

When project contains multiple cucumber feature files:

```
specs: [
  featuresPath + '**/*.feature'
],
```

And we are targeting a specific feature with a tag

```
cucumberOpts: {
  tags: ['@working']
}
```

The test runner will open an browser window for each feature file regardless of if their are tests to run in that file.

**Comment by timbru31** [comment]
Having the same issue. Using `"wdio-cucumber-framework": "0.0.6"`

**Comment by jackmichel** [comment]
I am experiencing the same issue, also using "wdio-cucumber-framework": "0.0.6". 

Not a big deal for me when running tests locally but it creates a lot of noise when running tests through SauceLabs or BrowserStack.

**Comment by AndrewKeig** [comment]
Hi, any idea as to when we might get a fix on this?

**Comment by christian-bromann** [comment]
@AndrewKeig feel free to start working on it 😉

**Comment by dcypherthis** [comment]
👍 On this.  Especially when using tags.    Looks like it's spawning a child process for each feature file detected in the chosen features directory.  WDIO is only running the tests that are tagged but seems to still spawn a process for the total number of .feature files.  I'm going to look into this tonight and work on it if I have time.  @christian-bromann would you recommend I start here or look in WDIO directly?  Just figured I'd ask if you had any recommendations.

**Comment by christian-bromann** [comment]
I think though this (tagging) should be implemented project wide so it works across frameworks. However I am not sure about the implementation details.

**Comment by wirsingj** [comment]
Any update on this issue?  Thanks!

**Comment by Kshirodram** [comment]
Tagging in wdio-cucumber framework is not working for me as well. Any luck ? It's running all the test cases even after scenario based tagging.  :(

**Comment by timbru31** [comment]
See https://github.com/webdriverio/webdriverio/issues/1247#issuecomment-230595671

**Comment by christian-bromann** [comment]
This is a general problem and will be tackled in webdriverio/webdriverio#1247
