### ISSUE TITLE
stepResult.getAmbiguousStepDefinitions is not a function

### ISSUE THREAD

**Issue by vyacheslav-lonschakov** [webdriverio/wdio-cucumber-framework#81]
Hi, received this error in logs:
"stepResult.getAmbiguousStepDefinitions is not a function"

**Comment by JeremyAtEverwise** [comment]
I got this error when I reused the same step definition in both my When and Then files. The step name was being used globally, so I had to change the step wording so I could call a step in my When or Then file without triggering this error.
