### ISSUE TITLE
npm test fail after npm install

### ISSUE THREAD

**Issue by FlippieCoetser** [webdriverio/wdio-cucumber-framework#84]
I intend to help tackle several of the open issues. 
However, after `git clone` the repo and running `npm install` I attempted to run `npm test`, which fails.
See below:

![image](https://user-images.githubusercontent.com/3672126/33205917-e06763fa-d108-11e7-9e02-cce4ae06dcf0.png)

After spending several hours of troubleshooting, I still fail at getting `npm test` to run.
Can anyone help me?

If I can get this sorted then I can contribute to tackling some issues...

**Comment by FlippieCoetser** [comment]
can confirm, I am using a Windows machine.

**Comment by nicangeli** [comment]
I think this is a git bash thing not properly handling single quotes.

@FlippieCoetser if you change the npm:test in package.json to: 
```
    "test:unit": "mocha --compilers js:babel-core/register \"./test/!(adapter.spec).js\"",
```

Likewise for the coverage command. 

@christian-bromann If this is something you'd like to support I can make a PR

**Comment by christian-bromann** [comment]
> If this is something you'd like to support I can make a PR

please do, thanks!
