### ISSUE TITLE
print gherkin syntax Given, When, Then while running the steps in the console.

### ISSUE THREAD

**Issue by JEHAL81** [webdriverio/wdio-cucumber-framework#86]
Print the Given, When, Then while running the steps in the console.

<img width="407" alt="screen shot 2017-11-30 at 21 49 08" src="https://user-images.githubusercontent.com/25979411/33456781-5a454ed0-d618-11e7-84bf-cd1c00bacacb.png">

Also, the User stories descriptions of a feature and feature tags.

**Comment by christian-bromann** [comment]
This issue was moved to webdriverio/wdio-spec-reporter#67

**Comment by christian-bromann** [comment]
I think you are talking about running Cucumber with the spec reporter. This is more an enhancement for the reporter as for the framework adapter. Feel free to propose a PR
