### ISSUE TITLE
Steps cannot use callbacks

### ISSUE THREAD

**Issue by DevSide** [webdriverio/wdio-cucumber-framework#94]
Wrapping steps which use callbacks instead of returning promises leads to this cucumber error:
"function uses multiple asynchronous interfaces: callback and promise"

This is causing by the setDefinitionFunctionWrapper which always returns a promise.

**Comment by christian-bromann** [comment]
@DevSide can you provide more details on which package versions you are using, maybe a reproducible example would be ideal.

**Comment by DevSide** [comment]
Yes ! Here is a step which failed:
```js
Then('It should fail', callback => {
  callback();
})
```

**Comment by christian-bromann** [comment]
@DevSide yes, so since you can use promises you can't use callback anymore which are not needed.

**Comment by DevSide** [comment]
Not needed ? Promise api doesn't replace callback api :smile: . 
You should document that _callbacks are not supported_.

**Comment by christian-bromann** [comment]
> Not needed ? Promise api doesn't replace callback api 😄

You think? I don't know why you would want to use callbacks if promises are supported.

> You should document that Cucumber step callbacks are not supported.

Would you mind open a PR?
