### ISSUE TITLE
wdio-cucumber-framework : how can i Multiple scenarios from single feature file ?

### ISSUE THREAD

**Issue by amolebhojane** [webdriverio/wdio-cucumber-framework#97]
how i can run multiple scenarios from single feature files.. requirement is after successful scenario execution browser should closed automatically and for next scenarios it should open again and execute

**Comment by christian-bromann** [comment]
> how i can run multiple scenarios from single feature files

I think this is not possible. There can be only one Scenario per feature file. Please create multiple feature files which then will be run in parallel. If you have further questions join our  [![Gitter](https://badges.gitter.im/webdriverio/webdriverio.svg)](https://gitter.im/webdriverio/webdriverio?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge). Thanks!

**Comment by amolebhojane** [comment]
Thanks @christian-bromann for your quick help..  is there any way to mark scenario with tagnames and execute it which i want..  
eg.

there are 4 scenarios with tag names @one, @two, @three, @four..  if i want to execute scenarios with tag names @one and @three..  how can i achieve it?

I have tried using --cucumberOpts.tags="@one,@three"  but it is executing all the scenarios from feature file.

thanks

**Comment by christian-bromann** [comment]
> how can i achieve it?

scenarios in feature files are basically spec files which you can define when running the wdio command, e.g.
```js
wdio --spec ./features/some.feature
```

**Comment by amolebhojane** [comment]
@christian-bromann  Thanks .   i have single  feature file which has following four scenarios.. in normal wedriver-cucumber we can achieve these specifiying tagname **--cucumberOpts.tags="@one,@three"**  
feature file:
  -scenario one 
  -scenario two
  -scenario three
  -scenario four

if i want to run only scenario two and three .. is it possible here?

**Comment by christian-bromann** [comment]
Sure:
```sh
$ wdio --spec ./features/scenario1.feature,./features/scenario2.feature
```

**Comment by janardanb** [comment]
Thanks @christian-bromann for your help.

but i observed that empty browser  opens for each feature file with no tests targeted??  is it bug or do i miss something??

**Comment by christian-bromann** [comment]
It is a known bug
