### ISSUE TITLE
Update stack-chain dependency to 2.0.0

### ISSUE THREAD

**Issue by rbardini** [webdriverio/wdio-cucumber-framework#99]
[`cucumber`](https://github.com/cucumber/cucumber-js) currently uses `stack-chain@2.0.0`, while `wdio-cucumber-framework` uses `stack-chain@1.3.7`. This difference can cause _"Conflicting version of stack-chain found."_ errors in [some cases](https://github.com/AndreasMadsen/stack-chain/blob/master/index.js#L10), for example when running WebdriverIO with [`esm`](https://github.com/standard-things/esm) to enable ES modules.

Updating `stack-chain` to version 2.0.0 should prevent this issue.

**Comment by christian-bromann** [comment]
@rbardini would you mind creating a PR?

**Comment by christian-bromann** [comment]
Ok, closing then
